# docker-compose.yml

version: "3.8" 

services: 
  app:
    image: 834988222517.dkr.ecr.eu-north-1.amazonaws.com/lab-projesi/app:latest
    container_name: nextjs_app
    ports:
      - "3001:3000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine 
    container_name: nginx_proxy
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Sertifika dosyalarını sunucudan konteynere bağlıyoruz
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    depends_on:
      - app