version: "3.8" 

services: 
  app:
    build: . 
    container_name: nextjs_app
    ports:
      - "3001:3000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine 
    container_name: nginx_proxy
    ports:
      - "80:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app 
