version: "3.8" 

services: 
  app:
    build: . 
    container_name: nextjs_app
    ports:
      - "3001:3000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine 
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - app 
